### ISSUE TITLE
remove previous message when doing a new log

### ISSUE THREAD

**Issue by hieronymousch** [stevenbeeckman/logchain#3]
Add log message: good that author is kept in form, message should be blanc though (shows now the previous message)

**Comment by hieronymousch** [comment]
(working on edge)

**Comment by hieronymousch** [comment]
IE does not retain previous data

**Comment by stevenbeeckman** [comment]
Solved with release v1.0.2 , download it on the [Releases](https://github.com/stevenbeeckman/logchain/releases/) page.
